# https://taskfile.dev

version: "3"

dotenv: [".env"]

tasks:
  entg:
    desc: regenerate ent code after we make any edits to `schema/*.go`
    cmds:
      - go run ./cmd/entg .

  migrate:
    desc: run db migration script for against ent scheam
    # deps: [entg]
    cmds:
      - go run ./cmd/dbmigrate

  tag:
    desc: tag the current commit
    cmds:
      - git tag -a v0.0.2 -m "updates"
      - git push origin v0.0.2

  release:
    desc: release binary to github
    cmds:
      - goreleaser release --clean --skip=validate
